### ISSUE TITLE
Unhandled Exception While Scanning ME3 Game Files

### ISSUE THREAD

**Issue by Gwardinen** [MassEffectModder/MassEffectModder#11]
I get the unhandled exception below while attempting to scan the game files of Mass Effect 3 after installing it and unpacking the DLC.

```
************** Exception Text **************
System.Exception: Exception of type 'System.Exception' was thrown.
   at StreamHelpers.StreamHelpers.ReadToBuffer(Stream stream, Int32 count) in c:\stuff\MassEffectModder\Helpers\StreamHelpers\StreamIO.cs:line 35
   at StreamHelpers.StreamHelpers.ReadToBuffer(Stream stream, UInt32 count) in c:\stuff\MassEffectModder\Helpers\StreamHelpers\StreamIO.cs:line 40
   at MassEffectModder.Package..ctor(String filename, Boolean memMode, Boolean headerOnly) in c:\stuff\MassEffectModder\MassEffectModder\Package.cs:line 444
   at MassEffectModder.TreeScan.FindTextures(List`1 textures, String packagePath) in c:\stuff\MassEffectModder\MassEffectModder\TexExplorerTree.cs:line 241
   at MassEffectModder.TreeScan.PrepareListOfTextures(TexExplorer texEplorer, MainWindow mainWindow, Installer installer, Boolean force) in c:\stuff\MassEffectModder\MassEffectModder\TexExplorerTree.cs:line 171
   at MassEffectModder.TexExplorer.Run() in c:\stuff\MassEffectModder\MassEffectModder\TexExplorer.cs:line 184
   at MassEffectModder.MainWindow.massEffect3ToolStripMenuItem_Click(Object sender, EventArgs e) in c:\stuff\MassEffectModder\MassEffectModder\MainWindow.cs:line 95
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
MassEffectModder
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///F:/fkers/Downloads/MassEffectModder/MassEffectModder.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
StreamHelpers
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///F:/fkers/Downloads/MassEffectModder/StreamHelpers.DLL
----------------------------------------
LZO2Helper
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///F:/fkers/Downloads/MassEffectModder/LZO2Helper.DLL
----------------------------------------
ZlibHelper
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///F:/fkers/Downloads/MassEffectModder/ZlibHelper.DLL
----------------------------------------
```

**Comment by aquadran** [comment]
check your game files after unpack DLC

**Comment by Gwardinen** [comment]
Aha, yeah, it seems like there were some missing or corrupt localisation files in DLC_EXP_Pack001. Scan completed now.
